const RUTE_SEARCH_DATA =
  [{
    "District": "Oslo",
    "ID": 1000026620,
    "Name": "Sinsen T-bane #",
    "Rank": 2147483647,
    "ShortName": null,
    "Stops": [{
      "District": "Oslo",
      "ID": 3012100,
      "Name": "Sinsen [T-bane]",
      "Rank": 0,
      "ShortName": "SIS",
      "Stops": [],
      "Type": 0,
      "X": 599570,
      "Y": 6645780,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 0
    }, {
      "District": "Oslo",
      "ID": 3012101,
      "Name": "Sinsen T [buss]",
      "Rank": 0,
      "ShortName": "SIST",
      "Stops": [],
      "Type": 0,
      "X": 599598,
      "Y": 6645678,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 0
    }],
    "Type": 1,
    "X": 0,
    "Y": 0,
    "Zone": null
  }, {
    "District": "Oslo",
    "ID": 1000023145,
    "Name": "Sinsenkrysset #",
    "Rank": 2147483647,
    "ShortName": null,
    "Stops": [{
      "District": "Oslo",
      "ID": 3012103,
      "Name": "Sinsenkrysset (Ringv. mot syd)",
      "Rank": 0,
      "ShortName": "SIKR",
      "Stops": [],
      "Type": 0,
      "X": 599797,
      "Y": 6645723,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 0
    }, {
      "District": "Oslo",
      "ID": 3012104,
      "Name": "Sinsenkrysset (nordsiden Trh.vn)",
      "Rank": 0,
      "ShortName": "SKRN",
      "Stops": [],
      "Type": 0,
      "X": 599771,
      "Y": 6645872,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 0
    }, {
      "District": "Oslo",
      "ID": 3012105,
      "Name": "Sinsenkrysset [trikk]",
      "Rank": 0,
      "ShortName": "SS",
      "Stops": [],
      "Type": 0,
      "X": 599648,
      "Y": 6645973,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 0
    }, {
      "District": "Oslo",
      "ID": 3012102,
      "Name": "Sinsenkrysset (sydsiden Trh.vn)",
      "Rank": 0,
      "ShortName": "SKRS",
      "Stops": [],
      "Type": 0,
      "X": 599823,
      "Y": 6645810,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 0
    }, {
      "District": "Oslo",
      "ID": 3012106,
      "Name": "Sinsenkrysset (Ringv. mot nord)",
      "Rank": 0,
      "ShortName": "SKKR",
      "Stops": [],
      "Type": 0,
      "X": 599805,
      "Y": 6645767,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 0
    }],
    "Type": 1,
    "X": 0,
    "Y": 0,
    "Zone": null
  }, {
    "__type": "Stop:#Topp2009",
    "District": "Oslo",
    "ID": 3012100,
    "Name": "Sinsen [T-bane]",
    "Rank": 1000,
    "ShortName": "SIS",
    "Stops": [],
    "Type": 0,
    "X": 599570,
    "Y": 6645780,
    "Zone": "1",
    "AlightingAllowed": false,
    "ArrivalTime": null,
    "BoardingAllowed": false,
    "DepartureTime": null,
    "Deviations": [],
    "Lines": [],
    "RealTimeStop": true,
    "StopPoints": [],
    "WalkingDistance": 0
  }, {
    "__type": "Stop:#Topp2009",
    "District": "Oslo",
    "ID": 3011482,
    "Name": "Sinsen kirke",
    "Rank": 900,
    "ShortName": "SISK",
    "Stops": [],
    "Type": 0,
    "X": 599878,
    "Y": 6645157,
    "Zone": "1",
    "AlightingAllowed": false,
    "ArrivalTime": null,
    "BoardingAllowed": false,
    "DepartureTime": null,
    "Deviations": [],
    "Lines": [],
    "RealTimeStop": true,
    "StopPoints": [],
    "WalkingDistance": 0
  }, {
    "__type": "Stop:#Topp2009",
    "District": "Oslo",
    "ID": 3012101,
    "Name": "Sinsen T [buss]",
    "Rank": 900,
    "ShortName": "SIST",
    "Stops": [],
    "Type": 0,
    "X": 599598,
    "Y": 6645678,
    "Zone": "1",
    "AlightingAllowed": false,
    "ArrivalTime": null,
    "BoardingAllowed": false,
    "DepartureTime": null,
    "Deviations": [],
    "Lines": [],
    "RealTimeStop": true,
    "StopPoints": [],
    "WalkingDistance": 0
  }, {
    "__type": "Stop:#Topp2009",
    "District": "Ringsaker",
    "ID": 4121824,
    "Name": "Sinsenkrysset",
    "Rank": 800,
    "ShortName": "",
    "Stops": [],
    "Type": 0,
    "X": 593724,
    "Y": 6744967,
    "Zone": "472",
    "AlightingAllowed": false,
    "ArrivalTime": null,
    "BoardingAllowed": false,
    "DepartureTime": null,
    "Deviations": [],
    "Lines": [],
    "RealTimeStop": true,
    "StopPoints": [],
    "WalkingDistance": 0
  }, {
    "__type": "Stop:#Topp2009",
    "District": "Oslo",
    "ID": 3012104,
    "Name": "Sinsenkrysset (nordsiden Trh.vn)",
    "Rank": 800,
    "ShortName": "SKRN",
    "Stops": [],
    "Type": 0,
    "X": 599771,
    "Y": 6645872,
    "Zone": "1",
    "AlightingAllowed": false,
    "ArrivalTime": null,
    "BoardingAllowed": false,
    "DepartureTime": null,
    "Deviations": [],
    "Lines": [],
    "RealTimeStop": true,
    "StopPoints": [],
    "WalkingDistance": 0
  }, {
    "__type": "Stop:#Topp2009",
    "District": "Oslo",
    "ID": 3012106,
    "Name": "Sinsenkrysset (Ringv. mot nord)",
    "Rank": 800,
    "ShortName": "SKKR",
    "Stops": [],
    "Type": 0,
    "X": 599805,
    "Y": 6645767,
    "Zone": "1",
    "AlightingAllowed": false,
    "ArrivalTime": null,
    "BoardingAllowed": false,
    "DepartureTime": null,
    "Deviations": [],
    "Lines": [],
    "RealTimeStop": true,
    "StopPoints": [],
    "WalkingDistance": 0
  }, {
    "__type": "Stop:#Topp2009",
    "District": "Oslo",
    "ID": 3012103,
    "Name": "Sinsenkrysset (Ringv. mot syd)",
    "Rank": 800,
    "ShortName": "SIKR",
    "Stops": [],
    "Type": 0,
    "X": 599797,
    "Y": 6645723,
    "Zone": "1",
    "AlightingAllowed": false,
    "ArrivalTime": null,
    "BoardingAllowed": false,
    "DepartureTime": null,
    "Deviations": [],
    "Lines": [],
    "RealTimeStop": true,
    "StopPoints": [],
    "WalkingDistance": 0
  }, {
    "__type": "Stop:#Topp2009",
    "District": "Oslo",
    "ID": 3012102,
    "Name": "Sinsenkrysset (sydsiden Trh.vn)",
    "Rank": 800,
    "ShortName": "SKRS",
    "Stops": [],
    "Type": 0,
    "X": 599823,
    "Y": 6645810,
    "Zone": "1",
    "AlightingAllowed": false,
    "ArrivalTime": null,
    "BoardingAllowed": false,
    "DepartureTime": null,
    "Deviations": [],
    "Lines": [],
    "RealTimeStop": true,
    "StopPoints": [],
    "WalkingDistance": 0
  }, {
    "__type": "Stop:#Topp2009",
    "District": "Oslo",
    "ID": 3012105,
    "Name": "Sinsenkrysset [trikk]",
    "Rank": 800,
    "ShortName": "SS",
    "Stops": [],
    "Type": 0,
    "X": 599648,
    "Y": 6645973,
    "Zone": "1",
    "AlightingAllowed": false,
    "ArrivalTime": null,
    "BoardingAllowed": false,
    "DepartureTime": null,
    "Deviations": [],
    "Lines": [],
    "RealTimeStop": true,
    "StopPoints": [],
    "WalkingDistance": 0
  }, {
    "__type": "Stop:#Topp2009",
    "District": "Oslo",
    "ID": 3011407,
    "Name": "Sinsenterrassen",
    "Rank": 800,
    "ShortName": "SSTE",
    "Stops": [],
    "Type": 0,
    "X": 599427,
    "Y": 6645416,
    "Zone": "1",
    "AlightingAllowed": false,
    "ArrivalTime": null,
    "BoardingAllowed": false,
    "DepartureTime": null,
    "Deviations": [],
    "Lines": [],
    "RealTimeStop": true,
    "StopPoints": [],
    "WalkingDistance": 0
  }, {
    "__type": "Stop:#Topp2009",
    "District": "Oslo",
    "ID": 3012086,
    "Name": "Sinsenveien",
    "Rank": 800,
    "ShortName": "SSV",
    "Stops": [],
    "Type": 0,
    "X": 600174,
    "Y": 6645473,
    "Zone": "1",
    "AlightingAllowed": false,
    "ArrivalTime": null,
    "BoardingAllowed": false,
    "DepartureTime": null,
    "Deviations": [],
    "Lines": [],
    "RealTimeStop": true,
    "StopPoints": [],
    "WalkingDistance": 0
  }, {
    "District": "Oslo",
    "ID": 1000023143,
    "Name": "Sinsen kirke",
    "Rank": -1,
    "ShortName": null,
    "Stops": [{
      "District": "Oslo",
      "ID": 3010437,
      "Name": "Sæveruds plass",
      "Rank": 0,
      "ShortName": "SÆP",
      "Stops": [],
      "Type": 0,
      "X": 599149,
      "Y": 6645526,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 30, "LineName": "30", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 15
    }, {
      "District": "Oslo",
      "ID": 3011400,
      "Name": "Carl Berners plass [T-bane]",
      "Rank": 0,
      "ShortName": "CBP",
      "Stops": [],
      "Type": 0,
      "X": 599400,
      "Y": 6644460,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 4, "LineName": "4", "Transportation": 8}, {
        "LineID": 5,
        "LineName": "5",
        "Transportation": 8
      }, {"LineID": 6, "LineName": "6", "Transportation": 8}, {"LineID": 2006, "LineName": "6", "Transportation": 8}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 15
    }, {
      "District": "Oslo",
      "ID": 3011401,
      "Name": "Carl Berners plass (i Trondh.vn)",
      "Rank": 0,
      "ShortName": "CBPT",
      "Stops": [],
      "Type": 0,
      "X": 599298,
      "Y": 6644577,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 17, "LineName": "17", "Transportation": 7}, {
        "LineID": 31,
        "LineName": "31",
        "Transportation": 2
      }, {"LineID": 33, "LineName": "33", "Transportation": 2}, {
        "LineID": 57,
        "LineName": "57",
        "Transportation": 2
      }, {"LineID": 301, "LineName": "301", "Transportation": 2}, {
        "LineID": 302,
        "LineName": "302",
        "Transportation": 2
      }, {"LineID": 309, "LineName": "309", "Transportation": 2}, {
        "LineID": 321,
        "LineName": "321",
        "Transportation": 2
      }, {"LineID": 363, "LineName": "363", "Transportation": 2}, {
        "LineID": 2031,
        "LineName": "31E",
        "Transportation": 2
      }, {"LineID": 3801, "LineName": "F1", "Transportation": 1}, {
        "LineID": 5153,
        "LineName": "153",
        "Transportation": 2
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 15
    }, {
      "District": "Oslo",
      "ID": 3011405,
      "Name": "Rosenhoff",
      "Rank": 0,
      "ShortName": "ROHF",
      "Stops": [],
      "Type": 0,
      "X": 599385,
      "Y": 6644987,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 17, "LineName": "17", "Transportation": 7}, {
        "LineID": 31,
        "LineName": "31",
        "Transportation": 2
      }, {"LineID": 33, "LineName": "33", "Transportation": 2}, {
        "LineID": 301,
        "LineName": "301",
        "Transportation": 2
      }, {"LineID": 302, "LineName": "302", "Transportation": 2}, {
        "LineID": 309,
        "LineName": "309",
        "Transportation": 2
      }, {"LineID": 321, "LineName": "321", "Transportation": 2}, {
        "LineID": 363,
        "LineName": "363",
        "Transportation": 2
      }, {"LineID": 2031, "LineName": "31E", "Transportation": 2}, {
        "LineID": 3801,
        "LineName": "F1",
        "Transportation": 1
      }, {"LineID": 5153, "LineName": "153", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 12
    }, {
      "District": "Oslo",
      "ID": 3011407,
      "Name": "Sinsenterrassen",
      "Rank": 0,
      "ShortName": "SSTE",
      "Stops": [],
      "Type": 0,
      "X": 599427,
      "Y": 6645416,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 17, "LineName": "17", "Transportation": 7}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 11
    }, {
      "District": null,
      "ID": 0,
      "Name": null,
      "Rank": 0,
      "ShortName": null,
      "Stops": [],
      "Type": 0,
      "X": 0,
      "Y": 0,
      "Zone": null,
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [],
      "RealTimeStop": false,
      "StopPoints": [],
      "WalkingDistance": 7
    }, {
      "District": "Oslo",
      "ID": 3011409,
      "Name": "Fjellhaug",
      "Rank": 0,
      "ShortName": "FJHA",
      "Stops": [],
      "Type": 0,
      "X": 599749,
      "Y": 6645008,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 57, "LineName": "57", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 5
    }, {
      "District": "Oslo",
      "ID": 3011413,
      "Name": "Haslevangen (i Økernveien)",
      "Rank": 0,
      "ShortName": "HAVA",
      "Stops": [],
      "Type": 0,
      "X": 600326,
      "Y": 6644466,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 60, "LineName": "60", "Transportation": 2}, {
        "LineID": 105,
        "LineName": "105",
        "Transportation": 2
      }, {"LineID": 345, "LineName": "345", "Transportation": 2}, {
        "LineID": 435,
        "LineName": "435",
        "Transportation": 2
      }, {"LineID": 3905, "LineName": "N5", "Transportation": 2}, {
        "LineID": 5153,
        "LineName": "153",
        "Transportation": 2
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 14
    }, {
      "District": "Oslo",
      "ID": 3011415,
      "Name": "Einars vei",
      "Rank": 0,
      "ShortName": "EINV",
      "Stops": [],
      "Type": 0,
      "X": 599945,
      "Y": 6644362,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 21, "LineName": "21", "Transportation": 2}, {
        "LineID": 28,
        "LineName": "28",
        "Transportation": 2
      }, {"LineID": 345, "LineName": "345", "Transportation": 2}, {
        "LineID": 435,
        "LineName": "435",
        "Transportation": 2
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 16
    }, {
      "District": null,
      "ID": 0,
      "Name": null,
      "Rank": 0,
      "ShortName": null,
      "Stops": [],
      "Type": 0,
      "X": 0,
      "Y": 0,
      "Zone": null,
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [],
      "RealTimeStop": false,
      "StopPoints": [],
      "WalkingDistance": 14
    }, {
      "District": "Oslo",
      "ID": 3011417,
      "Name": "Carl Berners plass T [buss]",
      "Rank": 0,
      "ShortName": "CBPH",
      "Stops": [],
      "Type": 0,
      "X": 599358,
      "Y": 6644504,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 21, "LineName": "21", "Transportation": 2}, {
        "LineID": 28,
        "LineName": "28",
        "Transportation": 2
      }, {"LineID": 345, "LineName": "345", "Transportation": 2}, {
        "LineID": 435,
        "LineName": "435",
        "Transportation": 2
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 15
    }, {
      "District": "Oslo",
      "ID": 3011482,
      "Name": "Sinsen kirke",
      "Rank": 0,
      "ShortName": "SISK",
      "Stops": [],
      "Type": 0,
      "X": 599878,
      "Y": 6645157,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 57, "LineName": "57", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 0
    }, {
      "District": "Oslo",
      "ID": 3011484,
      "Name": "Løren",
      "Rank": 0,
      "ShortName": "LØR",
      "Stops": [],
      "Type": 0,
      "X": 600168,
      "Y": 6645044,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 57, "LineName": "57", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 5
    }, {
      "District": null,
      "ID": 0,
      "Name": null,
      "Rank": 0,
      "ShortName": null,
      "Stops": [],
      "Type": 0,
      "X": 0,
      "Y": 0,
      "Zone": null,
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [],
      "RealTimeStop": false,
      "StopPoints": [],
      "WalkingDistance": 6
    }, {
      "District": "Oslo",
      "ID": 3011486,
      "Name": "OBS Løren",
      "Rank": 0,
      "ShortName": "OBSL",
      "Stops": [],
      "Type": 0,
      "X": 600607,
      "Y": 6644877,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 57, "LineName": "57", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 11
    }, {
      "District": "Oslo",
      "ID": 3012003,
      "Name": "Haslelund (i Standardveien)",
      "Rank": 0,
      "ShortName": "HASLU",
      "Stops": [],
      "Type": 0,
      "X": 601155,
      "Y": 6644371,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 23, "LineName": "23", "Transportation": 2}, {
        "LineID": 24,
        "LineName": "24",
        "Transportation": 2
      }, {"LineID": 68, "LineName": "68", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 14
    }, {
      "District": "Oslo",
      "ID": 3012086,
      "Name": "Sinsenveien",
      "Rank": 0,
      "ShortName": "SSV",
      "Stops": [],
      "Type": 0,
      "X": 600174,
      "Y": 6645473,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 23, "LineName": "23", "Transportation": 2}, {
        "LineID": 24,
        "LineName": "24",
        "Transportation": 2
      }, {"LineID": 107, "LineName": "107", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 8
    }, {
      "District": "Oslo",
      "ID": 3012087,
      "Name": "Lørenvangen",
      "Rank": 0,
      "ShortName": "LØRV",
      "Stops": [],
      "Type": 0,
      "X": 600529,
      "Y": 6645260,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 23, "LineName": "23", "Transportation": 2}, {
        "LineID": 24,
        "LineName": "24",
        "Transportation": 2
      }, {"LineID": 107, "LineName": "107", "Transportation": 2}, {
        "LineID": 3803,
        "LineName": "F3",
        "Transportation": 1
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 11
    }, {
      "District": "Oslo",
      "ID": 3012100,
      "Name": "Sinsen [T-bane]",
      "Rank": 0,
      "ShortName": "SIS",
      "Stops": [],
      "Type": 0,
      "X": 599570,
      "Y": 6645780,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 4, "LineName": "4", "Transportation": 8}, {
        "LineID": 5,
        "LineName": "5",
        "Transportation": 8
      }, {"LineID": 6, "LineName": "6", "Transportation": 8}, {"LineID": 2006, "LineName": "6", "Transportation": 8}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 11
    }, {
      "District": "Oslo",
      "ID": 3012101,
      "Name": "Sinsen T [buss]",
      "Rank": 0,
      "ShortName": "SIST",
      "Stops": [],
      "Type": 0,
      "X": 599598,
      "Y": 6645678,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 31, "LineName": "31", "Transportation": 2}, {
        "LineID": 33,
        "LineName": "33",
        "Transportation": 2
      }, {"LineID": 301, "LineName": "301", "Transportation": 2}, {
        "LineID": 302,
        "LineName": "302",
        "Transportation": 2
      }, {"LineID": 309, "LineName": "309", "Transportation": 2}, {
        "LineID": 321,
        "LineName": "321",
        "Transportation": 2
      }, {"LineID": 363, "LineName": "363", "Transportation": 2}, {
        "LineID": 3801,
        "LineName": "F1",
        "Transportation": 1
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 9
    }, {
      "District": "Oslo",
      "ID": 3012102,
      "Name": "Sinsenkrysset (sydsiden Trh.vn)",
      "Rank": 0,
      "ShortName": "SKRS",
      "Stops": [],
      "Type": 0,
      "X": 599823,
      "Y": 6645810,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 31, "LineName": "31", "Transportation": 2}, {
        "LineID": 33,
        "LineName": "33",
        "Transportation": 2
      }, {"LineID": 58, "LineName": "58", "Transportation": 2}, {
        "LineID": 301,
        "LineName": "301",
        "Transportation": 2
      }, {"LineID": 302, "LineName": "302", "Transportation": 2}, {
        "LineID": 309,
        "LineName": "309",
        "Transportation": 2
      }, {"LineID": 321, "LineName": "321", "Transportation": 2}, {
        "LineID": 363,
        "LineName": "363",
        "Transportation": 2
      }, {"LineID": 3801, "LineName": "F1", "Transportation": 1}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 11
    }, {
      "District": "Oslo",
      "ID": 3012103,
      "Name": "Sinsenkrysset (Ringv. mot syd)",
      "Rank": 0,
      "ShortName": "SIKR",
      "Stops": [],
      "Type": 0,
      "X": 599797,
      "Y": 6645723,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 23, "LineName": "23", "Transportation": 2}, {
        "LineID": 24,
        "LineName": "24",
        "Transportation": 2
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 10
    }, {
      "District": "Oslo",
      "ID": 3012104,
      "Name": "Sinsenkrysset (nordsiden Trh.vn)",
      "Rank": 0,
      "ShortName": "SKRN",
      "Stops": [],
      "Type": 0,
      "X": 599771,
      "Y": 6645872,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 31, "LineName": "31", "Transportation": 2}, {
        "LineID": 33,
        "LineName": "33",
        "Transportation": 2
      }, {"LineID": 58, "LineName": "58", "Transportation": 2}, {
        "LineID": 301,
        "LineName": "301",
        "Transportation": 2
      }, {"LineID": 302, "LineName": "302", "Transportation": 2}, {
        "LineID": 309,
        "LineName": "309",
        "Transportation": 2
      }, {"LineID": 321, "LineName": "321", "Transportation": 2}, {
        "LineID": 363,
        "LineName": "363",
        "Transportation": 2
      }, {"LineID": 3801, "LineName": "F1", "Transportation": 1}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 11
    }, {
      "District": "Oslo",
      "ID": 3012105,
      "Name": "Sinsenkrysset [trikk]",
      "Rank": 0,
      "ShortName": "SS",
      "Stops": [],
      "Type": 0,
      "X": 599648,
      "Y": 6645973,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 17, "LineName": "17", "Transportation": 7}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 13
    }, {
      "District": "Oslo",
      "ID": 3012112,
      "Name": "Grefsen stasjon (Ringvn mot syd)",
      "Rank": 0,
      "ShortName": "GRST",
      "Stops": [],
      "Type": 0,
      "X": 599535,
      "Y": 6646136,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 23, "LineName": "23", "Transportation": 2}, {
        "LineID": 24,
        "LineName": "24",
        "Transportation": 2
      }, {"LineID": 3803, "LineName": "F3", "Transportation": 1}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 16
    }],
    "Type": 2,
    "X": 599898,
    "Y": 6645180,
    "Zone": null
  }, {
    "District": "Oslo",
    "ID": 1000023144,
    "Name": "Sinsen skole",
    "Rank": -1,
    "ShortName": null,
    "Stops": [{
      "District": "Oslo",
      "ID": 3010437,
      "Name": "Sæveruds plass",
      "Rank": 0,
      "ShortName": "SÆP",
      "Stops": [],
      "Type": 0,
      "X": 599149,
      "Y": 6645526,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 30, "LineName": "30", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 11
    }, {
      "District": "Oslo",
      "ID": 3010441,
      "Name": "Nordpolen skole",
      "Rank": 0,
      "ShortName": "NOSK",
      "Stops": [],
      "Type": 0,
      "X": 599043,
      "Y": 6646091,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 30, "LineName": "30", "Transportation": 2}, {
        "LineID": 58,
        "LineName": "58",
        "Transportation": 2
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 15
    }, {
      "District": "Oslo",
      "ID": 3010442,
      "Name": "Haarklous plass",
      "Rank": 0,
      "ShortName": "HAAP",
      "Stops": [],
      "Type": 0,
      "X": 599129,
      "Y": 6645806,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 30, "LineName": "30", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 15
    }, {
      "District": "Oslo",
      "ID": 3011405,
      "Name": "Rosenhoff",
      "Rank": 0,
      "ShortName": "ROHF",
      "Stops": [],
      "Type": 0,
      "X": 599385,
      "Y": 6644987,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 17, "LineName": "17", "Transportation": 7}, {
        "LineID": 31,
        "LineName": "31",
        "Transportation": 2
      }, {"LineID": 33, "LineName": "33", "Transportation": 2}, {
        "LineID": 301,
        "LineName": "301",
        "Transportation": 2
      }, {"LineID": 302, "LineName": "302", "Transportation": 2}, {
        "LineID": 309,
        "LineName": "309",
        "Transportation": 2
      }, {"LineID": 321, "LineName": "321", "Transportation": 2}, {
        "LineID": 363,
        "LineName": "363",
        "Transportation": 2
      }, {"LineID": 2031, "LineName": "31E", "Transportation": 2}, {
        "LineID": 3801,
        "LineName": "F1",
        "Transportation": 1
      }, {"LineID": 5153, "LineName": "153", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 12
    }, {
      "District": "Oslo",
      "ID": 3011407,
      "Name": "Sinsenterrassen",
      "Rank": 0,
      "ShortName": "SSTE",
      "Stops": [],
      "Type": 0,
      "X": 599427,
      "Y": 6645416,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 17, "LineName": "17", "Transportation": 7}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 7
    }, {
      "District": null,
      "ID": 0,
      "Name": null,
      "Rank": 0,
      "ShortName": null,
      "Stops": [],
      "Type": 0,
      "X": 0,
      "Y": 0,
      "Zone": null,
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [],
      "RealTimeStop": false,
      "StopPoints": [],
      "WalkingDistance": 12
    }, {
      "District": "Oslo",
      "ID": 3011409,
      "Name": "Fjellhaug",
      "Rank": 0,
      "ShortName": "FJHA",
      "Stops": [],
      "Type": 0,
      "X": 599749,
      "Y": 6645008,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 57, "LineName": "57", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 10
    }, {
      "District": "Oslo",
      "ID": 3011482,
      "Name": "Sinsen kirke",
      "Rank": 0,
      "ShortName": "SISK",
      "Stops": [],
      "Type": 0,
      "X": 599878,
      "Y": 6645157,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 57, "LineName": "57", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 7
    }, {
      "District": "Oslo",
      "ID": 3011484,
      "Name": "Løren",
      "Rank": 0,
      "ShortName": "LØR",
      "Stops": [],
      "Type": 0,
      "X": 600168,
      "Y": 6645044,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 57, "LineName": "57", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 11
    }, {
      "District": null,
      "ID": 0,
      "Name": null,
      "Rank": 0,
      "ShortName": null,
      "Stops": [],
      "Type": 0,
      "X": 0,
      "Y": 0,
      "Zone": null,
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [],
      "RealTimeStop": false,
      "StopPoints": [],
      "WalkingDistance": 13
    }, {
      "District": "Oslo",
      "ID": 3012080,
      "Name": "Aker sykehus (nordsiden Trh.vn)",
      "Rank": 0,
      "ShortName": "ASY",
      "Stops": [],
      "Type": 0,
      "X": 600447,
      "Y": 6646200,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 31, "LineName": "31", "Transportation": 2}, {
        "LineID": 33,
        "LineName": "33",
        "Transportation": 2
      }, {"LineID": 58, "LineName": "58", "Transportation": 2}, {
        "LineID": 301,
        "LineName": "301",
        "Transportation": 2
      }, {"LineID": 302, "LineName": "302", "Transportation": 2}, {
        "LineID": 309,
        "LineName": "309",
        "Transportation": 2
      }, {"LineID": 321, "LineName": "321", "Transportation": 2}, {
        "LineID": 363,
        "LineName": "363",
        "Transportation": 2
      }, {"LineID": 2031, "LineName": "31E", "Transportation": 2}, {
        "LineID": 3801,
        "LineName": "F1",
        "Transportation": 1
      }, {"LineID": 5153, "LineName": "153", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 15
    }, {
      "District": "Oslo",
      "ID": 3012081,
      "Name": "Aker sykehus (sydsiden Trh.vn)",
      "Rank": 0,
      "ShortName": "AKSY",
      "Stops": [],
      "Type": 0,
      "X": 600418,
      "Y": 6646152,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 31, "LineName": "31", "Transportation": 2}, {
        "LineID": 33,
        "LineName": "33",
        "Transportation": 2
      }, {"LineID": 58, "LineName": "58", "Transportation": 2}, {
        "LineID": 301,
        "LineName": "301",
        "Transportation": 2
      }, {"LineID": 309, "LineName": "309", "Transportation": 2}, {
        "LineID": 321,
        "LineName": "321",
        "Transportation": 2
      }, {"LineID": 363, "LineName": "363", "Transportation": 2}, {
        "LineID": 2031,
        "LineName": "31E",
        "Transportation": 2
      }, {"LineID": 3801, "LineName": "F1", "Transportation": 1}, {
        "LineID": 5153,
        "LineName": "153",
        "Transportation": 2
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 14
    }, {
      "District": "Oslo",
      "ID": 3012086,
      "Name": "Sinsenveien",
      "Rank": 0,
      "ShortName": "SSV",
      "Stops": [],
      "Type": 0,
      "X": 600174,
      "Y": 6645473,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 23, "LineName": "23", "Transportation": 2}, {
        "LineID": 24,
        "LineName": "24",
        "Transportation": 2
      }, {"LineID": 107, "LineName": "107", "Transportation": 2}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 10
    }, {
      "District": "Oslo",
      "ID": 3012087,
      "Name": "Lørenvangen",
      "Rank": 0,
      "ShortName": "LØRV",
      "Stops": [],
      "Type": 0,
      "X": 600529,
      "Y": 6645260,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 23, "LineName": "23", "Transportation": 2}, {
        "LineID": 24,
        "LineName": "24",
        "Transportation": 2
      }, {"LineID": 107, "LineName": "107", "Transportation": 2}, {
        "LineID": 3803,
        "LineName": "F3",
        "Transportation": 1
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 14
    }, {
      "District": "Oslo",
      "ID": 3012100,
      "Name": "Sinsen [T-bane]",
      "Rank": 0,
      "ShortName": "SIS",
      "Stops": [],
      "Type": 0,
      "X": 599570,
      "Y": 6645780,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 4, "LineName": "4", "Transportation": 8}, {
        "LineID": 5,
        "LineName": "5",
        "Transportation": 8
      }, {"LineID": 6, "LineName": "6", "Transportation": 8}, {"LineID": 2006, "LineName": "6", "Transportation": 8}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 5
    }, {
      "District": "Oslo",
      "ID": 3012101,
      "Name": "Sinsen T [buss]",
      "Rank": 0,
      "ShortName": "SIST",
      "Stops": [],
      "Type": 0,
      "X": 599598,
      "Y": 6645678,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 31, "LineName": "31", "Transportation": 2}, {
        "LineID": 33,
        "LineName": "33",
        "Transportation": 2
      }, {"LineID": 301, "LineName": "301", "Transportation": 2}, {
        "LineID": 302,
        "LineName": "302",
        "Transportation": 2
      }, {"LineID": 309, "LineName": "309", "Transportation": 2}, {
        "LineID": 321,
        "LineName": "321",
        "Transportation": 2
      }, {"LineID": 363, "LineName": "363", "Transportation": 2}, {
        "LineID": 3801,
        "LineName": "F1",
        "Transportation": 1
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 3
    }, {
      "District": "Oslo",
      "ID": 3012102,
      "Name": "Sinsenkrysset (sydsiden Trh.vn)",
      "Rank": 0,
      "ShortName": "SKRS",
      "Stops": [],
      "Type": 0,
      "X": 599823,
      "Y": 6645810,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 31, "LineName": "31", "Transportation": 2}, {
        "LineID": 33,
        "LineName": "33",
        "Transportation": 2
      }, {"LineID": 58, "LineName": "58", "Transportation": 2}, {
        "LineID": 301,
        "LineName": "301",
        "Transportation": 2
      }, {"LineID": 302, "LineName": "302", "Transportation": 2}, {
        "LineID": 309,
        "LineName": "309",
        "Transportation": 2
      }, {"LineID": 321, "LineName": "321", "Transportation": 2}, {
        "LineID": 363,
        "LineName": "363",
        "Transportation": 2
      }, {"LineID": 3801, "LineName": "F1", "Transportation": 1}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 4
    }, {
      "District": "Oslo",
      "ID": 3012103,
      "Name": "Sinsenkrysset (Ringv. mot syd)",
      "Rank": 0,
      "ShortName": "SIKR",
      "Stops": [],
      "Type": 0,
      "X": 599797,
      "Y": 6645723,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 23, "LineName": "23", "Transportation": 2}, {
        "LineID": 24,
        "LineName": "24",
        "Transportation": 2
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 3
    }, {
      "District": "Oslo",
      "ID": 3012104,
      "Name": "Sinsenkrysset (nordsiden Trh.vn)",
      "Rank": 0,
      "ShortName": "SKRN",
      "Stops": [],
      "Type": 0,
      "X": 599771,
      "Y": 6645872,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 31, "LineName": "31", "Transportation": 2}, {
        "LineID": 33,
        "LineName": "33",
        "Transportation": 2
      }, {"LineID": 58, "LineName": "58", "Transportation": 2}, {
        "LineID": 301,
        "LineName": "301",
        "Transportation": 2
      }, {"LineID": 302, "LineName": "302", "Transportation": 2}, {
        "LineID": 309,
        "LineName": "309",
        "Transportation": 2
      }, {"LineID": 321, "LineName": "321", "Transportation": 2}, {
        "LineID": 363,
        "LineName": "363",
        "Transportation": 2
      }, {"LineID": 3801, "LineName": "F1", "Transportation": 1}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 5
    }, {
      "District": "Oslo",
      "ID": 3012105,
      "Name": "Sinsenkrysset [trikk]",
      "Rank": 0,
      "ShortName": "SS",
      "Stops": [],
      "Type": 0,
      "X": 599648,
      "Y": 6645973,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 17, "LineName": "17", "Transportation": 7}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 6
    }, {
      "District": "Oslo",
      "ID": 3012110,
      "Name": "Grefsen [tog]",
      "Rank": 0,
      "ShortName": "GF",
      "Stops": [],
      "Type": 0,
      "X": 599445,
      "Y": 6646290,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 9103, "LineName": "L3", "Transportation": 6}, {
        "LineID": 9130,
        "LineName": "R30",
        "Transportation": 6
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 12
    }, {
      "District": "Oslo",
      "ID": 3012111,
      "Name": "Grefsen stasjon [trikk]",
      "Rank": 0,
      "ShortName": "GFS",
      "Stops": [],
      "Type": 0,
      "X": 599529,
      "Y": 6646291,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 13, "LineName": "13", "Transportation": 7}, {
        "LineID": 17,
        "LineName": "17",
        "Transportation": 7
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 11
    }, {
      "District": "Oslo",
      "ID": 3012112,
      "Name": "Grefsen stasjon (Ringvn mot syd)",
      "Rank": 0,
      "ShortName": "GRST",
      "Stops": [],
      "Type": 0,
      "X": 599535,
      "Y": 6646136,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 23, "LineName": "23", "Transportation": 2}, {
        "LineID": 24,
        "LineName": "24",
        "Transportation": 2
      }, {"LineID": 3803, "LineName": "F3", "Transportation": 1}],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 10
    }, {
      "District": "Oslo",
      "ID": 3012113,
      "Name": "Grefsen stasjon (Ringv mot nord)",
      "Rank": 0,
      "ShortName": "GFST",
      "Stops": [],
      "Type": 0,
      "X": 599547,
      "Y": 6646198,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 23, "LineName": "23", "Transportation": 2}, {
        "LineID": 24,
        "LineName": "24",
        "Transportation": 2
      }, {"LineID": 107, "LineName": "107", "Transportation": 2}, {
        "LineID": 3803,
        "LineName": "F3",
        "Transportation": 1
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 10
    }, {
      "District": "Oslo",
      "ID": 3012142,
      "Name": "Nordre Åsen",
      "Rank": 0,
      "ShortName": "NÅS",
      "Stops": [],
      "Type": 0,
      "X": 599814,
      "Y": 6646547,
      "Zone": "1",
      "AlightingAllowed": false,
      "ArrivalTime": null,
      "BoardingAllowed": false,
      "DepartureTime": null,
      "Deviations": [],
      "Lines": [{"LineID": 56, "LineName": "56", "Transportation": 2}, {
        "LineID": 2056,
        "LineName": "56B",
        "Transportation": 2
      }],
      "RealTimeStop": true,
      "StopPoints": [],
      "WalkingDistance": 16
    }],
    "Type": 2,
    "X": 599712,
    "Y": 6645587,
    "Zone": null
  }];

export default RUTE_SEARCH_DATA;